# Change only if your display supports it!
# high FPS consumes more CPU!
# Default: 60
fps = 60

# Renders a small margin btw line numbers and the actual content
# Default: false
line_numbers_margin = false

# Number of spaces to insert instead of tab
# Default: 2
tab_width = 2

# Renders 1px width lines where there is a tabstop
# Default: true
tab_lines = true

# Font for code.
# Absolute path to font file is preferred.
# Relative path to font file with respect to app executable also works.
# Default: "assets/fonts/JetBrains Mono Regular Nerd Font Complete.ttf"
# Example: "C:/Windows/Fonts/consola.ttf"
# code_font = "assets/fonts/JetBrains Mono Regular Nerd Font Complete.ttf"
code_font = "assets/fonts/SauceCodeProNerdFont-Regular.ttf"

# Font size
# Default: 16
font_size = 16

# Characters which separate words or which act as delimiters for word.
word_separators = " \n\r.!\t;:\\/+-*&%<>=(){}[]\"',|~^#@`$"

# Window size, when launched.
[window]
  # Default: 1080
  width = 1080
  # Default: 720
  height = 720

[colorscheme]
  bg = "#24272e"
  fg = "#e1e3e4"
  red = "#e06c75"
  orange = "#d19a66"
  yellow = "#828a9a"
  green = "#98c379"
  cyan = "#f69c5e"
  blue = "#61afef"
  purple = "#c678dd"
  white = "#e1e3e4"
  black = "#181a1c"
  gray = "#5c6370"
  # RRGGBBAA color code for highlight
  highlight = "#61afef30"
  comment = "#5a6477"
  # RRGGBBAA color code for scrollbar
  scrollbar = "#9dd274aa"

[cpp_token_colors]
  semicolon = "#828a9a"
  comma = "#828a9a"
  escape_backslash = "#828a9a"
  bracket = "#828a9a"
  square_bracket = "#828a9a"
  curly_bracket = "#828a9a"
  character = "#f69c5e"
  string = "#eacb64"
  comment = "#5a6477"
  multiline_comment = "#5a6477"
  operator = "#72cce8"
  keyword = "#ff6578"
  preprocessor_directive = "#ff6578"
  identifier = "#e1e3e4"
  number = "#ba9cf3"
  function = "#a5e179"
  header = "#eacb64"

[scrolling]
  # scroll sensitivity is how many pixels to scroll when
  # a scroll event is occurred
  # default value: 60
  sensitivity = 60
  # scroll acceleration is how fast the scrolling should happen
  # value: 0.0 to 1.0
  # 0.0 => doesn't even scroll
  # 1.0 => instantly scrolls to desired scroll point
  # [0.35 - 0.5] => smooth scrolling
  # default value: 0.45
  acceleration = 0.2

[caret]
  color = "#abb2bf"
  # Caret styles: ibeam, block
  style = "ibeam"
  ibeam_width = 2
