# Change only if your display supports it!
# high FPS consumes more CPU processing time!
# Default: 60
fps = 60

# Renders a small margin btw line numbers and the actual content
# Default: false
line_numbers_margin = false

# Number of spaces to insert instead of tab
# Default: 2
tab_width = 2

# Renders 1px width lines where there is a tabstop
# Default: true
tab_lines = true

# Font size
# Default: 16
font_size = 16

[window]
  width = 1080
  height = 720

[colorscheme]
  bg = "#282c34"
  fg = "#abb2bf"
  red = "#e06c75"
  orange = "#d19a66"
  yellow = "#e5c07b"
  green = "#98c379"
  cyan = "#56b6c2"
  blue = "#61afef"
  purple = "#c678dd"
  white = "#abb2bf"
  black = "#282c34"
  gray = "#5c6370"
  # RRGGBBAA color code for highlight
  highlight = "#61afef44"
  comment = "#7f848e"
  # RRGGBBAA color code for scrollbar
  scrollbar = "#e5c07b88"

[cpp_token_colors]
  semicolon = "#e5c07b"
  comma = "#e5c07b"
  escape_backslash = "#e5c07b"
  bracket = "#e5c07b"
  square_bracket = "#e5c07b"
  curly_bracket = "#e5c07b"
  character = "#56b6c2"
  string = "#98c379"
  comment = "#7f848e"
  multiline_comment = "#7f848e"
  operator = "#e5c07b"
  keyword = "#e06c75"
  preprocessor_directive = "#d19a66"
  identifier = "#abb2bf"
  number = "#61afef"
  function = "#c678dd"
  header = "#56b6c2"

[scrolling]
  # scroll sensitivity is how many pixels to scroll when
  # a scroll event is occurred
  # default value: 60
  sensitivity = 60
  # scroll acceleration is how fast the scrolling should happen
  # value: 0.0 to 1.0
  # 0.0 => doesn't even scroll
  # 1.0 => instantly scrolls to desired scroll point
  # [0.35 - 0.5] => smooth scrolling
  # default value: 0.45
  acceleration = 0.45

[cursor]
  color = "#abb2bf"
  # Cursor styles: ibeam, block
  style = "ibeam"
  ibeam_width = 2