[window]
  width = 1080
  height = 720

[colorscheme]
  bg = "#282c34"
  fg = "#abb2bf"
  red = "#e06c75"
  orange = "#d19a66"
  yellow = "#e5c07b"
  green = "#98c379"
  cyan = "#56b6c2"
  blue = "#61afef"
  purple = "#c678dd"
  white = "#abb2bf"
  black = "#282c34"
  gray = "#5c6370"
  highlight = "#e2be7d"
  comment = "#7f848e"

[scrolling]
  sensitivity = 50
  friction = 0.3

[cpp_token_colors]
  semicolon = "#e5c07b"
  comma = "#e5c07b"
  escape_backslash = "#e5c07b"
  bracket = "#e5c07b"
  square_bracket = "#e5c07b"
  curly_bracket = "#e5c07b"
  character = "#56b6c2"
  string = "#98c379"
  comment = "#7f848e"
  multiline_comment = "#7f848e"
  operator = "#c678dd"
  keyword = "#e06c75"
  preprocessor_directive = "#d19a66"
  identifier = "#abb2bf"
  number = "#61afef"
  function = "#c678dd"
